package com.example.demo.model;

public enum EstadoUsuario {
    INICIO,
    MENU_PRINCIPAL,
    ESPERANDO_DATA,
    ESPERANDO_RESPOSTA_GALERIA,
    RESERVA_ESPERANDO_DATA,
    RESERVA_ESPERANDO_HORARIO,
    RESERVA_ESPERANDO_NOME,
    RESERVA_CONFIRMACAO
}
