services:
  # 1. Banco de Dados (Versão 17 para evitar erros de diretório do Postgres 18)
  db-bot:
    image: postgres:17-alpine
    container_name: postgres_recanto
    restart: always
    environment:
      POSTGRES_USER: ${MEU_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MEU_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MEU_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network

  # 2. Servidor do WhatsApp (WPPConnect)
  wppconnect:
    build: ./wppconnect-server
    container_name: wppconnect_server
    restart: always
    ports:
      - "21465:21465"
    environment:
      - PORT=21465
      - SECRET_KEY=${WPP_SECRET_KEY}
      - WPPCONNECT_WEBHOOK_URL=http://bot-java:8080/webhook/whatsapp
    networks:
      - bot-network
    volumes:
      - ./dados-wpp/userDataDir:/usr/src/wpp-server/userDataDir
      - ./dados-wpp/tokens:/usr/src/wpp-server/tokens

  # 3. Cérebro do Bot (Java Spring Boot)
  bot-java:
    build: .
    container_name: bot_java_recanto
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db-bot:
        condition: service_started
      wppconnect:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-bot:5432/${MEU_POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${MEU_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${MEU_POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - WPPCONNECT_URL=http://wppconnect:21465
      - WPPCONNECT_SECRET_KEY=${WPP_SECRET_KEY}
      # 👇 AS VARIÁVEIS NOVAS INJETADAS AQUI! 👇
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_AUTH_TOKEN=${API_AUTH_TOKEN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_DEFAULT_EMAIL=${ADMIN_DEFAULT_EMAIL:-usuario@gamb.com}
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_DEFAULT_PASSWORD:-SenhaMaster123}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge